DROP DATABASE IF EXISTS PhoenixEnterpriseDB;
GO

CREATE DATABASE PhoenixEnterpriseDB
GO

USE [PhoenixEnterpriseDB];
GO

CREATE TABLE PersonInfoTB(
	PAddressId INT IDENTITY(1,1) PRIMARY KEY,
	Mail VARCHAR(60) NOT NULL,
	Tlf VARCHAR(14),
	CPRNumber VARCHAR NOT NULL,
	Adress VARCHAR NOT NULL,
	PostalCode VARCHAR NOT NULL,
	Road VARCHAR NOT NULL,
	COUNTRY VARCHAR NOT NULL
);

CREATE TABLE PersonTB(
	PersonId INT IDENTITY(1,1) PRIMARY KEY,
	FirstName VARCHAR(28) NOT NULL,
	LastName VARCHAR(28) NOT NULL,
);

CREATE TABLE UsersTB(
	UserId INT IDENTITY(1,1) PRIMARY KEY,
	UPassWord VARCHAR NOT NULL,
	Balance DECIMAL,
);

CREATE TABLE EmployeeTB(
	EmplyeeId INT IDENTITY(1,1) PRIMARY KEY,
	EmplyeePassword VARCHAR NOT NULL,
	Tital VARCHAR NOT NULL,
	WorkMail VARCHAR(60)NOT NULL,
	WorkTlf VARCHAR(14)NOT NULL,
	AdminPassword VARCHAR,
	
	PersonId INT
);

CREATE TABLE ModeratorTB(
	ModeratorId INT IDENTITY(1,1) PRIMARY KEY,
	IsMod BIT NOT NULL,

	EmployeeId INT NOT NULL,
)

CREATE TABLE AdminTB(
	AdminId INT IDENTITY(1,1) PRIMARY KEY,
	IsAdmin BIT NOT NULL,

	EmployeeId INT NOT NULL,
);
